# Generated by Django 5.2.13 on 2026-05-09 16:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_pedido_ciudad_pedido_direccion_pedido_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pagado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
